name: Push model to Replicate

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # อัปเดตเป็น v4

      - name: Set up Cog
        uses: replicate/setup-cog@v2  # ตรวจสอบให้ใช้เวอร์ชันล่าสุด

      - name: Log in to Replicate
        run: echo "${{ secrets.REPLICATE_API_TOKEN }}" | cog login --token-stdin

      - name: Push model to Replicate
        run: cog push r8.im/varoriya/upscora
